# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x03otp\"\x1f\n\x0eSendOtpRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"\x1f\n\x0fSendOtpResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t2B\n\nOtpService\x12\x34\n\x07SendOtp\x12\x13.otp.SendOtpRequest\x1a\x14.otp.SendOtpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDOTPREQUEST']._serialized_start=22
  _globals['_SENDOTPREQUEST']._serialized_end=53
  _globals['_SENDOTPRESPONSE']._serialized_start=55
  _globals['_SENDOTPRESPONSE']._serialized_end=86
  _globals['_OTPSERVICE']._serialized_start=88
  _globals['_OTPSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
